export const countries = [
{
  "name":"Afghanistan",
  "phoneCode":"+93",
  "capital":"Kabul",
  "abbr":"AFN"
  },
  {
  "name":"Albania",
  "phoneCode":"+355",
  "capital":"Tirana",
  "abbr":"ALL"
  },
  {
  "name":"Algeria",
  "phoneCode":"+213",
  "capital":"Algiers",
  "abbr":"DZD"
  },
  {
  "name":"American Samoa",
  "phoneCode":"+1-684",
  "capital":"Pago Pago",
  "abbr":"USD"
  },
  {
  "name":"Andorra",
  "phoneCode":"+376",
  "capital":"Andorra la Vella",
  "abbr":"EUR"
  },
  {
  "name":"Angola",
  "phoneCode":"+244",
  "capital":"Luanda",
  "abbr":"AOA"
  },
  {
  "name":"Anguilla",
  "phoneCode":"+1-264",
  "capital":"‎The Valley",
  "abbr":"XCD"
  },
  {
  "name":"Antigua and Barbuda",
  "phoneCode":"+1-268",
  "capital":"Saint John's",
  "abbr":"XCD"
  },
  {
  "name":"Argentina",
  "phoneCode":"+54",
  "capital":"Buenos Aires",
  "abbr":"ARS"
  },
  {
  "name":"Armenia",
  "phoneCode":"+374",
  "capital":"Yerevan",
  "abbr":"AMD"
  },
  {
  "name":"Aruba",
  "phoneCode":"+297",
  "capital":"Oranjestad",
  "abbr":"AWG"
  },
  {
  "name":"Australia",
  "phoneCode":"+61",
  "capital":"Canberra",
  "abbr":"AUD"
  },
  {
  "name":"Austria",
  "phoneCode":"+43",
  "capital":"Vienna",
  "abbr":"EUR"
  },
  {
  "name":"Azerbaijan",
  "phoneCode":"+994",
  "capital":"Baku",
  "abbr":"AZN"
  },
  {
  "name":"Bahamas",
  "phoneCode":"+1-242",
  "capital":"Nassau",
  "abbr":"BSD"
  },
  {
  "name":"Bahrain",
  "phoneCode":"+973",
  "capital":"Manama",
  "abbr":"BHD"
  },
  {
  "name":"Bangladesh",
  "phoneCode":"+880",
  "capital":"Dhaka",
  "abbr":"BDT"
  },
  {
  "name":"Barbados",
  "phoneCode":"+1-246",
  "capital":"Bridgetown",
  "abbr":"BBD"
  },
  {
  "name":"Belarus",
  "phoneCode":"+375",
  "capital":"Minsk",
  "abbr":"BYN"
  },
  {
  "name":"Belgium",
  "phoneCode":"+32",
  "capital":"Brussels",
  "abbr":"EUR"
  },
  {
  "name":"Belize",
  "phoneCode":"+501",
  "capital":"Belmopan",
  "abbr":"BZD"
  },
  {
  "name":"Benin",
  "phoneCode":"+229",
  "capital":"Porto-Novo",
  "abbr":"XOF"
  },
  {
  "name":"Bermuda",
  "phoneCode":"+1-441",
  "capital":"Hamilton",
  "abbr":"BMD"
  },
  {
  "name":"Bhutan",
  "phoneCode":"+975",
  "capital":"Thimphu",
  "abbr":"INR"
  },
  {
  "name":"Bolivia",
  "phoneCode":"+591",
  "capital":"Sucre,La Paz",
  "abbr":"BOB"
  },
  {
  "name":"Bonaire, Sint Eustatius and Saba",
  "phoneCode":"+599",
  "capital":"Caribbean Netherlands",
  "abbr":"USD"
  },
  {
  "name":"Bosnia and Herzegovina",
  "phoneCode":"+387",
  "capital":"Sarajevo",
  "abbr":"BAM"
  },
  {
  "name":"Botswana",
  "phoneCode":"+267",
  "capital":"Gaborone",
  "abbr":"BWP"
  },
  {
  "name":"Brazil",
  "phoneCode":"+55",
  "capital":"Brasilia",
  "abbr":"BRL"
  },
  {
  "name":"British Indian Ocean Territory",
  "phoneCode":"+246",
  "capital":"British Colony, Indian Ocean",
  "abbr":"USD"
  },
  {
  "name":"British Virgin Islands",
  "phoneCode":"+1-284",
  "capital":"RoadTown",
  "abbr":"BVI"
  },
  {
  "name":"Brunei Darussalam",
  "phoneCode":"+673",
  "capital":"Brunei",
  "abbr":"BND"
  },
  {
  "name":"Bulgaria",
  "phoneCode":"+359",
  "capital":"Sofia",
  "abbr":"BGN"
  },
  {
  "name":"Burkina Faso",
  "phoneCode":"+226",
  "capital":"Ouagadougou",
  "abbr":"XOF"
  },
  {
  "name":"Burundi",
  "phoneCode":"+257",
  "capital":"Gitega",
  "abbr":"BIF"
  },
  {
  "name":"Cabo Verde",
  "phoneCode":"+238",
  "capital":"Praia",
  "abbr":"CVE"
  },
  {
  "name":"Cambodia",
  "phoneCode":"+855",
  "capital":"Phnom Penh",
  "abbr":"KHR"
  },
  {
  "name":"Cameroon",
  "phoneCode":"+237",
  "capital":"Yaounde",
  "abbr":"XAF"
  },
  {
  "name":"Canada",
  "phoneCode":"+1",
  "capital":"Ottawa",
  "abbr":"CAD"
  },
  {
  "name":"Cayman Islands",
  "phoneCode":"+1-345",
  "capital":"George Town",
  "abbr":"KYD"
  },
  {
  "name":"Central African Republic",
  "phoneCode":"+236",
  "capital":"Bangui",
  "abbr":"XAF"
  },
  {
  "name":"Chad",
  "phoneCode":"+235",
  "capital":"N'Djamena",
  "abbr":"XAF"
  },
  {
  "name":"Chile",
  "phoneCode":"+56",
  "capital":"Santiago",
  "abbr":"CLP"
  },
  {
  "name":"China",
  "phoneCode":"+86",
  "capital":"Beijing",
  "abbr":"CNY"
  },
  {
  "name":"Colombia",
  "phoneCode":"+57",
  "capital":"Bogotá",
  "abbr":"COP"
  },
  {
  "name":"Comoros",
  "phoneCode":"+269",
  "capital":"Moroni",
  "abbr":"KMF"
  },
  {
  "name":"Cook Islands",
  "phoneCode":"+682",
  "capital":"Avarua",
  "abbr":"NZD"
  },
  {
  "name":"Costa Rica",
  "phoneCode":"+506",
  "capital":"San Jose",
  "abbr":"CRC"
  },
  {
  "name":"Croatia",
  "phoneCode":"+385",
  "capital":"Zagreb",
  "abbr":"HRK"
  },
  {
  "name":"Cuba",
  "phoneCode":"+53",
  "capital":"Havana",
  "abbr":"CUC"
  },
  {
  "name":"Curaçao",
  "phoneCode":"+599",
  "capital":"Willemstad",
  "abbr":"ANG"
  },
  {
  "name":"Cyprus",
  "phoneCode":"+357",
  "capital":"Nicosia",
  "abbr":"EUR"
  },
  {
  "name":"Democratic Republic Of The Congo",
  "phoneCode":"+243",
  "capital":"Kinshasa",
  "abbr":"CDF"
  },
  {
  "name":"Denmark",
  "phoneCode":"+45",
  "capital":"Copenhagen",
  "abbr":"DKK"
  },
  {
  "name":"Djibouti",
  "phoneCode":"+253",
  "capital":"Djibouti (city)",
  "abbr":"DJF"
  },
  {
  "name":"Dominica",
  "phoneCode":"+1-767",
  "capital":"Roseau",
  "abbr":"XCD"
  },
  {
  "name":"Dominican Republic",
  "phoneCode":"+1-809",
  "capital":"Santo Domingo",
  "abbr":"DOP"
  },
  {
  "name":"Ecuador",
  "phoneCode":"+593",
  "capital":"Quito",
  "abbr":"USD"
  },
  {
  "name":"Egypt",
  "phoneCode":"+20",
  "capital":"Cairo",
  "abbr":"EGP"
  },
  {
  "name":"El Salvador",
  "phoneCode":"+503",
  "capital":"San Salvador",
  "abbr":"SVC"
  },
  {
  "name":"Equatorial Guinea",
  "phoneCode":"+240",
  "capital":"Malabo,Oyala",
  "abbr":"XAF"
  },
  {
  "name":"Eritrea",
  "phoneCode":"+291",
  "capital":"Asmara",
  "abbr":"ERN"
  },
  {
  "name":"Estonia",
  "phoneCode":"+372",
  "capital":"Tallinn",
  "abbr":"EUR"
  },
  {
  "name":"Ethiopia",
  "phoneCode":"+251",
  "capital":"Addis Ababa",
  "abbr":"ETB"
  },
  {
  "name":"Falkland Islands",
  "phoneCode":"+500",
  "capital":"FK",
  "abbr":"FKP"
  },
  {
  "name":"Faroe Islands",
  "phoneCode":"+298",
  "capital":"STANLEY",
  "abbr":"DKK"
  },
  {
  "name":"Federated States of Micronesia",
  "phoneCode":"+691",
  "capital":"Palikir",
  "abbr":"USD"
  },
  {
  "name":"Fiji",
  "phoneCode":"+679",
  "capital":"Suva",
  "abbr":"FJD"
  },
  {
  "name":"Finland",
  "phoneCode":"+358",
  "capital":"Helsinki",
  "abbr":"EUR"
  },
  {
  "name":"France",
  "phoneCode":"+33",
  "capital":"Paris",
  "abbr":"EUR"
  },
  {
  "name":"French Guiana",
  "phoneCode":"+594",
  "capital":"Cayenne",
  "abbr":"EUR"
  },
  {
  "name":"French Polynesia",
  "phoneCode":"+689",
  "capital":"Papeete",
  "abbr":"XPF"
  },
  {
  "name":"Gabon",
  "phoneCode":"+241",
  "capital":"Libreville",
  "abbr":"XAF"
  },
  {
  "name":"Gambia",
  "phoneCode":"+220",
  "capital":"Banjul",
  "abbr":"GMD"
  },
  {
  "name":"Georgia",
  "phoneCode":"+995",
  "capital":"Tbilisi",
  "abbr":"GEL"
  },
  {
  "name":"Germany",
  "phoneCode":"+49",
  "capital":"Berlin",
  "abbr":"EUR"
  },
  {
  "name":"Ghana",
  "phoneCode":"+233",
  "capital":"Accra",
  "abbr":"GHS"
  },
  {
  "name":"Gibraltar",
  "phoneCode":"+350",
  "capital":"Gibraltar",
  "abbr":"GIP"
  },
  {
  "name":"Greece",
  "phoneCode":"+30",
  "capital":"Athens",
  "abbr":"EUR"
  },
  {
  "name":"Greenland",
  "phoneCode":"+299",
  "capital":"Nuuk",
  "abbr":"DKK"
  },
  {
  "name":"Grenada",
  "phoneCode":" +1-473",
  "capital":"Saint George's",
  "abbr":"XCD"
  },
  {
  "name":"Guadeloupe",
  "phoneCode":"+590",
  "capital":"Basse-Terre",
  "abbr":"EUR"
  },
  {
  "name":"Guam",
  "phoneCode":"+1-671",
  "capital":"Hagatna",
  "abbr":"USD"
  },
  {
  "name":"Guatemala",
  "phoneCode":"+502",
  "capital":"Guatemala City",
  "abbr":"GTQ"
  },
  {
  "name":"Guinea",
  "phoneCode":"+224",
  "capital":"Conakry",
  "abbr":"GNF"
  },
  {
  "name":"Guinea-Bissau",
  "phoneCode":"+245",
  "capital":"Bissau",
  "abbr":"XOF"
  },
  {
  "name":"Guyana",
  "phoneCode":"+592",
  "capital":"Georgetown",
  "abbr":"GYD"
  },
  {
  "name":"Haiti",
  "phoneCode":"+509",
  "capital":"Port-au-Prince",
  "abbr":"HTG"
  },
  {
  "name":"Honduras",
  "phoneCode":"+504",
  "capital":"Tegucigalpa",
  "abbr":"HNL"
  },
  {
  "name":"Hong Kong",
  "phoneCode":"+852",
  "capital":"Hong Kong",
  "abbr":"HKD"
  },
  {
  "name":"Hungary",
  "phoneCode":"+36",
  "capital":"Budapest",
  "abbr":"HUF"
  },
  {
  "name":"Iceland",
  "phoneCode":"+354",
  "capital":"Reykjavik",
  "abbr":"ISK"
  },
  {
  "name":"India",
  "phoneCode":"+91",
  "capital":"New Delhi",
  "abbr":"INR"
  },
  {
  "name":"Indonesia",
  "phoneCode":"+62",
  "capital":"Jakarta",
  "abbr":"IDR"
  },
  {
  "name":"Iran",
  "phoneCode":"+98",
  "capital":"Tehran",
  "abbr":"IRR"
  },
  {
  "name":"Iraq",
  "phoneCode":"+964",
  "capital":"Baghdad",
  "abbr":"IQD"
  },
  {
  "name":"Ireland",
  "phoneCode":"+353",
  "capital":"Dublin",
  "abbr":"EUR"
  },
  {
  "name":"Israel",
  "phoneCode":"+972",
  "capital":"Jerusalem",
  "abbr":"ILS"
  },
  {
  "name":"Italy",
  "phoneCode":"+39",
  "capital":"Rome",
  "abbr":"EUR"
  },
  {
  "name":"Jamaica",
  "phoneCode":"+1-876",
  "capital":"Kingston",
  "abbr":"JMD"
  },
  {
  "name":"Japan",
  "phoneCode":"+81",
  "capital":"Tokyo",
  "abbr":"JPY"
  },
  {
  "name":"Jordan",
  "phoneCode":"+962",
  "capital":"Amman",
  "abbr":"JOD"
  },
  {
  "name":"Kazakhstan",
  "phoneCode":"+7",
  "capital":"Nur-Sultan",
  "abbr":"KZT"
  },
  {
  "name":"Kenya",
  "phoneCode":"+254",
  "capital":"Nairobi",
  "abbr":"KES"
  },
  {
  "name":"Kiribati",
  "phoneCode":"+686",
  "capital":"Tarawa",
  "abbr":"AUD"
  },
  {
  "name":"Kosovo",
  "phoneCode":"+383",
  "capital":"Pristina",
  "abbr":"RSD"
  },
  {
  "name":"Kuwait",
  "phoneCode":"+965",
  "capital":"Kuwait City",
  "abbr":"KWD"
  },
  {
  "name":"Kyrgyzstan",
  "phoneCode":"+996",
  "capital":"Bishkek",
  "abbr":"KGS"
  },
  {
  "name":"Laos",
  "phoneCode":"+856",
  "capital":"Vientiane",
  "abbr":"LAK"
  },
  {
  "name":"Latvia",
  "phoneCode":"+371",
  "capital":"Riga",
  "abbr":"LVL"
  },
  {
  "name":"Lebanon",
  "phoneCode":"+961",
  "capital":"Beirut",
  "abbr":"LBP"
  },
  {
  "name":"Lesotho",
  "phoneCode":"+266",
  "capital":"Maseru",
  "abbr":"LSL"
  },
  {
  "name":"Liberia",
  "phoneCode":"+231",
  "capital":"Monrovia",
  "abbr":"LRD"
  },
  {
  "name":"Libya",
  "phoneCode":"+218",
  "capital":"Tripoli",
  "abbr":"LYD"
  },
  {
  "name":"Liechtenstein",
  "phoneCode":"+423",
  "capital":"Vaduz",
  "abbr":"CHF"
  },
  {
  "name":"Lithuania",
  "phoneCode":"+370",
  "capital":"Vilnius",
  "abbr":"EUR"
  },
  {
  "name":"Luxembourg",
  "phoneCode":"+352",
  "capital":"Luxembourg(city)",
  "abbr":"EUR"
  },
  {
  "name":"Macao",
  "phoneCode":"+853",
  "capital":"Macao",
  "abbr":"MOP"
  },
  {
  "name":"Macedonia",
  "phoneCode":"+389",
  "capital":"Skopje",
  "abbr":"MKD"
  },
  {
  "name":"Madagascar",
  "phoneCode":"+261",
  "capital":"Antananarivo",
  "abbr":"MGA"
  },
  {
  "name":"Malawi",
  "phoneCode":"+265",
  "capital":"Lilongwe",
  "abbr":"MWK"
  },
  {
  "name":"Malaysia",
  "phoneCode":"+60",
  "capital":"Kuala Lumpur",
  "abbr":"MYR"
  },
  {
  "name":"Maldives",
  "phoneCode":"+960",
  "capital":"Male",
  "abbr":"MVR"
  },
  {
  "name":"Mali",
  "phoneCode":"+223",
  "capital":"Bamako",
  "abbr":"XOF"
  },
  {
  "name":"Malta",
  "phoneCode":"+356",
  "capital":"Valletta",
  "abbr":"EUR"
  },
  {
  "name":"Marshall Islands",
  "phoneCode":"+692",
  "capital":"Majuro",
  "abbr":"USD"
  },
  {
  "name":"Martinique",
  "phoneCode":"+596",
  "capital":"Fort-de-France",
  "abbr":"EUR"
  },
  {
  "name":"Mauritania",
  "phoneCode":"+222",
  "capital":"Nouakchott",
  "abbr":"MRU"
  },
  {
  "name":"Mauritius",
  "phoneCode":"+230",
  "capital":"Port Louis",
  "abbr":"MUR"
  },
  {
  "name":"Mayotte",
  "phoneCode":"+262",
  "capital":"Mamoudzou",
  "abbr":"EUR"
  },
  {
  "name":"Mexico",
  "phoneCode":"+52",
  "capital":"Mexico City",
  "abbr":"MXN"
  },
  {
  "name":"Micronesia",
  "phoneCode":"+691",
  "capital":"Palikir",
  "abbr":"USD"
  },
  {
  "name":"Moldova",
  "phoneCode":"+373",
  "capital":"Chisinau",
  "abbr":"MDL"
  },
  {
  "name":"Monaco",
  "phoneCode":"+377",
  "capital":"Monaco",
  "abbr":"EUR"
  },
  {
  "name":"Mongolia",
  "phoneCode":"+976",
  "capital":"Ulaanbaatar",
  "abbr":"MNT"
  },
  {
  "name":"Montenegro",
  "phoneCode":"+382",
  "capital":"Podgorica",
  "abbr":"EUR"
  },
  {
  "name":"Montserrat",
  "phoneCode":"+1-664",
  "capital":"Plymouth",
  "abbr":"XCD"
  },
  {
  "name":"Morocco",
  "phoneCode":"+212",
  "capital":"Rabat",
  "abbr":"MAD"
  },
  {
  "name":"Mozambique",
  "phoneCode":"+258",
  "capital":"Maputo",
  "abbr":"MZN"
  },
  {
  "name":"Myanmar",
  "phoneCode":"+95",
  "capital":"Naypyidaw",
  "abbr":"MMK"
  },
  {
  "name":"Namibia",
  "phoneCode":"+264",
  "capital":"Windhoek",
  "abbr":"NAD"
  },
  {
  "name":"Nauru",
  "phoneCode":"+674",
  "capital":"Yaren District",
  "abbr":"AUD"
  },
  {
  "name":"Nepal",
  "phoneCode":"+977",
  "capital":"Kathmandu",
  "abbr":"NPR"
  },
  {
  "name":"Netherlands",
  "phoneCode":"+31",
  "capital":"Amsterdam",
  "abbr":"EUR"
  },
  {
  "name":"Netherlands Antilles",
  "phoneCode":"+599",
  "capital":"willemstad",
  "abbr":"ANG"
  },
  {
  "name":"New Caledonia",
  "phoneCode":"+687",
  "capital":"Noumea",
  "abbr":"XPF"
  },
  {
  "name":"New Zealand",
  "phoneCode":"+64",
  "capital":"Wellington",
  "abbr":"NZD"
  },
  {
  "name":"Nicaragua",
  "phoneCode":"+505",
  "capital":"Managua",
  "abbr":"NIO"
  },
  {
  "name":"Niger",
  "phoneCode":"+227",
  "capital":"Niamey",
  "abbr":"XOF"
  },
  {
  "name":"Nigeria",
  "phoneCode":"+234",
  "capital":"Abuja",
  "abbr":"NGN"
  },
  {
  "name":"Niue",
  "phoneCode":"+683",
  "capital":"Alofi",
  "abbr":"NZD"
  },
  {
  "name":"Norfolk Island",
  "phoneCode":"+672",
  "capital":"‎Kingston",
  "abbr":"AUD"
  },
  {
  "name":"North Korea",
  "phoneCode":"+850",
  "capital":"Pyongyang",
  "abbr":"KPW"
  },
  {
  "name":"Northern Mariana Islands",
  "phoneCode":"+1-670",
  "capital":"Saipan",
  "abbr":"USD"
  },
  {
  "name":"North Macedonia",
  "phoneCode":"+389",
  "capital":"Skopje",
  "abbr":"MKD"
  },
  {
  "name":"Norway",
  "phoneCode":"+47",
  "capital":"Oslo",
  "abbr":"NOK"
  },
  {
  "name":"Oman",
  "phoneCode":"+968",
  "capital":"Muscat",
  "abbr":"OMR"
  },
  {
  "name":"Pakistan",
  "phoneCode":"+92",
  "capital":"Islamabad",
  "abbr":"PKR"
  },
  {
  "name":"Palau",
  "phoneCode":"+680",
  "capital":"Ngerulmud",
  "abbr":"USD"
  },
  {
  "name":"Panama",
  "phoneCode":"+507",
  "capital":"Panama City",
  "abbr":"PAB"
  },
  {
  "name":"Papua New Guinea",
  "phoneCode":"+675",
  "capital":"Port Moresby",
  "abbr":"PGK"
  },
  {
  "name":"Paraguay",
  "phoneCode":"+595",
  "capital":"Asunción",
  "abbr":"PYG"
  },
  {
  "name":"Peru",
  "phoneCode":"+51",
  "capital":"Lima",
  "abbr":"PEN"
  },
  {
  "name":"Philippines",
  "phoneCode":"+63",
  "capital":"Manila",
  "abbr":"PHP"
  },
  {
  "name":"Poland",
  "phoneCode":"+48",
  "capital":"Warsaw",
  "abbr":"PLN"
  },
  {
  "name":"Portugal",
  "phoneCode":"+351",
  "capital":"Lisbon",
  "abbr":"EUR"
  },
  {
  "name":"Puerto Rico",
  "phoneCode":"+1-787",
  "capital":"San Juan",
  "abbr":"USD"
  },
  {
  "name":"Qatar",
  "phoneCode":"+974",
  "capital":"Doha",
  "abbr":"QAR"
  },
  {
  "name":"Republic Of The Congo",
  "phoneCode":"+242",
  "capital":"Brazaville",
  "abbr":"CDF"
  },
  {
  "name":"Réunion",
  "phoneCode":"+262",
  "capital":"Saint-Denis",
  "abbr":"EUR"
  },
  {
  "name":"Romania",
  "phoneCode":"+40",
  "capital":"Bucharest",
  "abbr":"RON"
  },
  {
  "name":"Russia",
  "phoneCode":"+7",
  "capital":"Moscow",
  "abbr":"RUB"
  },
  {
  "name":"Rwanda",
  "phoneCode":"+250",
  "capital":"Kigali",
  "abbr":"RWF"
  },
  {
  "name":"Saint Barthélemy",
  "phoneCode":"+590",
  "capital":"Gustavia",
  "abbr":"EUR"
  },
  {
  "name":"Saint Helena",
  "phoneCode":"+290",
  "capital":"Jamestown",
  "abbr":"SHP"
  },
  {
  "name":"Saint Kitts and Nevis",
  "phoneCode":"+1-869",
  "capital":"Basseterre",
  "abbr":"XCD"
  },
  {
  "name":"Saint Martin",
  "phoneCode":"+590",
  "capital":"Marigot",
  "abbr":"EUR"
  },
  {
  "name":"Saint Pierre and Miquelon",
  "phoneCode":"+508",
  "capital":"Saint-Pierre",
  "abbr":"EUR"
  },
  {
  "name":"Saint Vincent and the Grenadines",
  "phoneCode":"+1-784",
  "capital":"Kingstown",
  "abbr":"XCD"
  },
  {
  "name":"Samoa",
  "phoneCode":"+685",
  "capital":"Apia",
  "abbr":"WST"
  },
  {
  "name":"San Marino",
  "phoneCode":"+378",
  "capital":"San Marino",
  "abbr":"EUR"
  },
  {
  "name":"São Tomé and Príncipe",
  "phoneCode":"+239",
  "capital":"São Tomé",
  "abbr":"STN"
  },
  {
  "name":"Saudi Arabia",
  "phoneCode":"+966",
  "capital":"Riyadh",
  "abbr":"SAR"
  },
  {
  "name":"Senegal",
  "phoneCode":"+221",
  "capital":"Dakar",
  "abbr":"XOF"
  },
  {
  "name":"Serbia",
  "phoneCode":"+381",
  "capital":"Belgrade",
  "abbr":"RSD"
  },
  {
  "name":"Seychelles",
  "phoneCode":"+248",
  "capital":"Victoria",
  "abbr":"SCR"
  },
  {
  "name":"Sierra Leone",
  "phoneCode":"+232",
  "capital":"Freetown",
  "abbr":"SLL"
  },
  {
  "name":"Singapore",
  "phoneCode":"+65",
  "capital":"Singapore",
  "abbr":"SGD"
  },
  {
  "name":"Sint Maarten (Dutch part)",
  "phoneCode":"+1-721",
  "capital":"Phillipsburg",
  "abbr":"SXM"
  },
  {
  "name":"Slovakia",
  "phoneCode":"+421",
  "capital":"Bratislava",
  "abbr":"SKK"
  },
  {
  "name":"Slovenia",
  "phoneCode":"+386",
  "capital":"Ljubljana",
  "abbr":"EUR"
  },
  {
  "name":"Solomon Islands",
  "phoneCode":"+677",
  "capital":"Honiara",
  "abbr":"SBD"
  },
  {
  "name":"Somalia",
  "phoneCode":"+252",
  "capital":"Mogadishu",
  "abbr":"SOS"
  },
  {
  "name":"South Africa",
  "phoneCode":"+27",
  "capital":"Pretoria, Cape Town, Bloemfontein ",
  "abbr":"ZAR"
  },
  {
  "name":"South Korea",
  "phoneCode":"+82",
  "capital":"Seoul",
  "abbr":"KRW"
  },
  {
  "name":"South Sudan",
  "phoneCode":"+211",
  "capital":"Juba",
  "abbr":"SSP"
  },
  {
  "name":"Spain",
  "phoneCode":"+34",
  "capital":"Madrid",
  "abbr":"EUR"
  },
  {
  "name":"Sri Lanka",
  "phoneCode":"+94",
  "capital":"Sri Jayawardenepura Kotte",
  "abbr":"LKR"
  },
  {
  "name":"Saint Lucia",
  "phoneCode":"+1-758",
  "capital":"Castries",
  "abbr":"XCD"
  },
  {
  "name":"Sudan",
  "phoneCode":"+249",
  "capital":"Khartoum",
  "abbr":"SDG"
  },
  {
  "name":"Suriname",
  "phoneCode":"+597",
  "capital":"Paramaribo",
  "abbr":"SRD"
  },
  {
  "name":"Swaziland",
  "phoneCode":"+268",
  "capital":"Mbabane",
  "abbr":"SZL"
  },
  {
  "name":"Sweden",
  "phoneCode":"+46",
  "capital":"Stockholm",
  "abbr":"SEK"
  },
  {
  "name":"Switzerland",
  "phoneCode":"+41",
  "capital":"Bern",
  "abbr":"CHE"
  },
  {
  "name":"Syrian Arab Republic",
  "phoneCode":"+963",
  "capital":"Damascus",
  "abbr":"SYP"
  },
  {
  "name":"Taiwan",
  "phoneCode":"+886",
  "capital":"Taipei",
  "abbr":"TWD"
  },
  {
  "name":"Tajikistan",
  "phoneCode":"+992",
  "capital":"Dushanbe",
  "abbr":"TJS"
  },
  {
  "name":"Tanzania",
  "phoneCode":"+255",
  "capital":"Dodoma",
  "abbr":"TZS"
  },
  {
  "name":"Thailand",
  "phoneCode":"+66",
  "capital":"Bangkok",
  "abbr":"THB"
  },
 
  {
  "name":"Timor-Leste",
  "phoneCode":"+670",
  "capital":"Dili",
  "abbr":"USD"
  },
  {
  "name":"Togo",
  "phoneCode":"+228",
  "capital":"Lomé",
  "abbr":"XOF"
  },
  {
  "name":"Tokelau",
  "phoneCode":"+690",
  "capital":"(UNDETERMINED)",
  "abbr":"NZD"
  },
  {
  "name":"Tonga",
  "phoneCode":"+676",
  "capital":"Nukuʻalofa",
  "abbr":"TOP"
  },
  {
  "name":"Trinidad and Tobago",
  "phoneCode":"+1-868",
  "capital":"Port of Spain",
  "abbr":"TTD"
  },
  {
  "name":"Tunisia",
  "phoneCode":"+216",
  "capital":"Tunis",
  "abbr":"TND"
  },
  {
  "name":"Turkey",
  "phoneCode":"+90",
  "capital":"Ankara",
  "abbr":"TRY"
  },
  {
  "name":"Turkmenistan",
  "phoneCode":"+993",
  "capital":"Ashgabat",
  "abbr":"TMT"
  },
  {
  "name":"Turks and Caicos Islands",
  "phoneCode":"+1-649",
  "capital":"Cockburn Town",
  "abbr":"USD"
  },
  {
  "name":"Tuvalu",
  "phoneCode":"+688",
  "capital":"Funafuti",
  "abbr":"AUD"
  },
  {
  "name":"Uganda",
  "phoneCode":"+256",
  "capital":"Kampala",
  "abbr":"UGX"
  },
  {
  "name":"Ukraine",
  "phoneCode":"+380",
  "capital":"Kyiv ",
  "abbr":"UAH"
  },
  {
  "name":"United Arab Emirates",
  "phoneCode":"+971",
  "capital":"Abu Dhabi",
  "abbr":"AED"
  },
  {
  "name":"United Kingdom",
  "phoneCode":"+44",
  "capital":"London",
  "abbr":"GBP"
  },
  {
  "name":"United States",
  "phoneCode":"+1",
  "capital":"Washington, D.C.",
  "abbr":"USD"
  },
  {
  "name":"Uruguay",
  "phoneCode":"+598",
  "capital":"Montevideo",
  "abbr":"UYI"
  },
  {
  "name":"U.S. Virgin Islands",
  "phoneCode":"+1-340",
  "capital":"CHARLOTTE AMALIE",
  "abbr":"XCD"
  },
  {
  "name":"Uzbekistan",
  "phoneCode":"+998",
  "capital":"Tashkent",
  "abbr":"UZS"
  },
  {
  "name":"Vanuatu",
  "phoneCode":"+678",
  "capital":"Port Vila",
  "abbr":"VUV"
  },
  {
  "name":"Vatican City",
  "phoneCode":"+39",
  "capital":"Vatican City",
  "abbr":"EUR"
  },
  {
  "name":"Venezuela",
  "phoneCode":"+58",
  "capital":"Caracas",
  "abbr":"VEF"
  },
  {
  "name":"Vietnam",
  "phoneCode":"+84",
  "capital":"Hanoi",
  "abbr":"VND"
  },
  {
  "name":"Wallis and Futuna",
  "phoneCode":"+681",
  "capital":"Mata Utu",
  "abbr":"XPF"
  },
  {
  "name":"Yemen",
  "phoneCode":"+967",
  "capital":"Sana'a",
  "abbr":"YER"
  },
  {
  "name":"Zambia",
  "phoneCode":"+260",
  "capital":"Lusaka",
  "abbr":"ZMW"
  },
  {
  "name":"Zimbabwe",
  "phoneCode":"+263",
  "capital":"Harare",
  "abbr":"ZWL"
  },
  ]